### ISSUE TITLE
req: add default pytest.ini

### ISSUE THREAD

**Issue by jedie** [SpotlightKid/python-package-cookiecutter#1]
What's about a default pytest.ini ?

**Comment by SpotlightKid** [comment]
What would you want to put in there?

I'd like to keep the number of configuration files to a minimum. Otherwise you soon end up with:

* `setup.cfg`
* `tox.ini`
* `.flake8`
* `.pydocstyle[.ini]`
* `pytest.ini`
* `.bumpversion.cfg`
* ... and so on.

You can put the configuration for most of these programs also in `setup.cfg` or `tox.ini`. So I could have put all the tox stuff in `setup.cfg` as well, but the tox configuration can get quite big for more complex projects, so I like to keep it separate. The configuration for flake8, pycodestyle, pydocstyle and py.test, on the other hand, usually consist only of a few lines for each, so so I`like to keep it in one place to avoid repetition and inconsistent settings.

I usually only need to change py.test settings to set the Django settings module or to activate/deactivate py.test plugins.
